services:
  postgres:
    image: postgres
    container_name: postgres
    build:
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev